-- 1. ADD GOLD, TTL AND DEAD UNTIL TO PLAYER TABLE
ALTER TABLE `players`
  ADD COLUMN `gold` BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN `ttl` INT NOT NULL DEFAULT 360,
  ADD COLUMN `dead_until` DATETIME NULL;

-- 2. SET VERSION
UPDATE `s_version`
SET `version` = 3;